<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/5/12
 * Time: 23:32
 */

namespace app\components;
use app\models\AccessLog;
use Yii;
use app\models\Setting;

class Module extends \yii\base\Module
{
    /**
     * @inheritdoc
     */
    public function init()
    {
//        \Yii::$app->setAliases([
//            'static'=>\Yii::$app->basePath.'/../../static/',
//        ]);
        $setting = Setting::getSetting();
        Yii::$app->params = array_merge(\Yii::$app->params , $setting);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        $module = $this->id;
        $controller = $action->controller->id;
        $actionName = $action->id;

        register_shutdown_function(
            function()use($module,$controller,$actionName)
            {
                $log = new AccessLog();
                $log->access_time = time();
                $log->method = call_user_func(
                    function($method)
                    {
                        $method = strtoupper($method);
                        $map = ['GET','POST','PUT','DELETE'];
                        if (in_array($method,$map))
                        {
                            return array_search($method,$map);
                        }
                        return -1;
                    }
                    ,$_SERVER['REQUEST_METHOD']);
                $log->module = $module;
                $log->controller = $controller;
                $log->action = $actionName;
                $log->from = array_key_exists('HTTP_X_REAL_IP',$_SERVER)?$_SERVER['HTTP_X_REAL_IP']:$_SERVER['REMOTE_ADDR'];
                $log->request = json_encode(['get'=>$_GET,'post'=>$_POST]);
                $log->save(false);
            }
        );
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}