<?php
namespace app\rbac\rules;

use app\models\Users;
use app\models\WxApp;
use yii\web\ForbiddenHttpException;

/**
 * 珠海魅族科技有限公司
 * Copyright (c) 2012 - 2013 meizu.com ZhuHai Inc. (http://www.meizu.com)
 * User: 陈晓发
 * Date: 2016/3/21
 * Time: 16:53
 */
abstract class WeixinAccessRule extends Rule
{
	const WEINXIN_PERMISSION_TYPE_SET_MENU = 0;

	public $appId = -1;
	/** @var Users */
	public $userModel = null;

	/** @var WxApp */
	public $appModel = null;

	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
		$this->appId = \Yii::$app->request->get('app_id');
		$this->userModel = \Yii::$app->getUser()->getIdentity();
		$this->appModel = WxApp::findOne($this->appId);
		if (empty($this->appModel))
		{
			throw new ForbiddenHttpException('You are not allowed to access this app');
		}
	}

	public function check()
	{
		if ($this->appModel->owner == $this->userModel->id)
		{
			return true;
		}
		$this->checkOperaPermission();
		return true;
	}

	abstract protected function checkOperaPermission();

}