<?php
/**


 * User: 陈晓发
 * Date: 2016/3/8
 * Time: 17:53
 */

namespace app\managers;

use app\exceptions\BusinessLogicException;
use app\models\WxApp;
use app\models\WxBind;
use app\models\WxUsers;
use app\weixin\api\AuthorizeApi;
use app\weixin\api\TemplateApi;
use app\weixin\api\TokenApi;
use \app\models\WxMenu;
use \app\weixin\api\MenuApi;
use app\weixin\api\UserInfoApi;
use app\weixin\exceptions\WeixinApiException;

/**
 * Class WeixinManager
 * @package app\managers
 * @property WxApp $appModel
 */
class WeixinManager extends Manager
{
	public static function getInstanceByAppId($wxAppId)
	{
		return WeixinManager::getInstance(['wxAppModel'=>WxApp::findOne(['id'=>$wxAppId])]);
	}
	/** @var WxApp $wxAppModel */
	public $wxAppModel = null;
	public $wx_access_token = null;

	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
		if (empty($this->wxAppModel))
		{
			BusinessLogicException::T('missing weixin app infomation');
		}
		if (
			is_null( $this->wxAppModel->wx_access_token ) ||
			$this->wxAppModel->wx_access_token_expire - 100 < time()
		)
		{
			$tokenApi = TokenApi::create($this->wxAppModel);
			if ($tokenApi->send() === false)
			{
				BusinessLogicException::T($tokenApi->getErrorString());
			}
			$this->wxAppModel->updateAccessToken($tokenApi->accessToken,$tokenApi->expire);
		}

	}


	public function setMenu()
	{

		$menuApi = MenuApi::create($this->wxAppModel);
		$firstLevel = WxMenu::find()->limit(3)->offset(0)->where(['status'=>1,'app_id'=>$this->wxAppModel->id])->andWhere('isnull(parent_id)')->all();
		/** @var WxMenu $button */
		foreach($firstLevel as $button)
		{
			switch($button->type)
			{
				case WxMenu::TYPE_LIST:
					$subButtons = [];
					foreach(WxMenu::findAll(['parent_id'=>$button->id,'status'=>1]) as $subButton)
					{
						$subButtons[] = MenuApi::createButtonByType($subButton->type,$subButton->name,$subButton->param);
					}
					$menuApi->addButtonList($button->name,$subButtons);
					break;
				default:
					$menuApi->addButton(MenuApi::createButtonByType($button->type,$button->name,$button->param));
			}
		}
		$menuApi->send();
	}

	/**
	 * @param $openId
	 * @return WxBind|null
	 */
	public function getBind($openId)
	{
		$bindModel = WxBind::findOne(['waid'=>$this->wxAppModel->id,'openid'=>$openId]);
		if (empty($bindModel))
		{
			$userInfoApi = UserInfoApi::create($this->wxAppModel);

			/** @var array $wxUserInfo */
			$wxUserInfo = $userInfoApi->getByOpenID($openId);
			if ($wxUserInfo === false)
			{
				WeixinApiException::T($userInfoApi->toString());
			}
			$wxUserModel = null;
			if ($wxUserInfo['unionid'])
			{//没有union id,可以判定首次访问
				$wxUserModel = WxUsers::findOne(['unionid'=>$wxUserInfo['unionid']]);
			}
			if (is_null($wxUserModel))
			{
				$wxUserModel = WxUsers::createFromWxUserInfo($wxUserInfo);
				$wxUserModel->save();
			}
			$bindModel = new WxBind();
			$bindModel->setAttributes(
				[
					'waid'=>$this->wxAppModel->id,
					'openid'=>$openId,
					'wuid'=>$wxUserModel->id,
					'groupid'=>$wxUserInfo['groupid'],
					'subscribe'=>$wxUserInfo['subscribe'],
					'create_time'=>time(),
					'update_time'=>time(),
				],false
			);
			$bindModel->save();
			$bindModel->setWxUser($wxUserModel);
		}
		return $bindModel;

	}


	public function authWithSnsapiBase()
	{
		$api = AuthorizeApi::create($this->wxAppModel);
		return  $api->authWithSnsapiBase();

	}

	public function sendSurveyNotify($templdateId,$openId)
	{
		$api = TemplateApi::create($this->wxAppModel);
		$api->setReceiver($openId);
		$api->setTemplateId($templdateId);
		if ($api->sendTemplate() === false)
		{
			BusinessLogicException::T('通信错误');
		}
		return true;

	}

}