<?php
/**


 * User: 陈晓发
 * Date: 2016/1/21
 * Time: 16:28
 */

namespace app\modules\weixin\controllers;


use app\weixin\Encrypter;
use app\weixin\exceptions\WeixinApiException;
use app\weixin\handler\Handler;
use app\weixin\Request;
use app\weixin\Response;
use app\managers\WeixinManager;

/**
 * Class IndexController
 * @package app\modules\weixin\controllers
 */
class IndexController extends WeixinController
{

	public function beforeAction($action)
	{
		return parent::beforeAction($action);
	}

	public function actionJoin()
	{
		$req = \Yii::$app->request;
		//配置验证
		if ($req->get('echostr',false) !== false)
		{
			return $req->get('echostr');
		}
	}

	public function actionIndex()
	{
		$wxReq = Request::decodeFromPost();
		if ($wxReq->success === false)
		{
			return '';
		}
		try
		{
			$mgr = WeixinManager::getInstance(['wxAppModel'=>$this->appModel]);
			$wxBind = $mgr->getBind($wxReq->getFromUserName());
			$wxUser = $wxBind->getWxUser();
			return Handler::dispatch($wxReq,$this->appModel,$wxUser);
		}
		catch(\Exception $e)
		{
			\Yii::error($e,WEIXIN_CATEGORY);
			return $wxReq->createTextResponse('服务器繁忙,请稍后再试.');
		}

	}


	public function afterAction($action, $result)
	{
		if ($result instanceof Response)
		{
			return parent::afterAction($action,$result->encode());
		}
		return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
	}

}