<?php
/**


 * User: 陈晓发
 * Date: 2016/3/8
 * Time: 17:42
 */

namespace app\modules\weixin\controllers;


use app\weixin\Encrypter;
use yii\web\Controller;
use app\models\WxApp;

/**
 * Class WeixinController
 * @package app\modules\weixin\controllers
 */
class WeixinController extends Controller
{
	protected $appId = null;
	/** @var WxApp $appModel */
	protected $appModel = null;
	protected $encrypter = null;


	/**
	 * 检查微信签名
	 * @return bool
	 */
	public function checkSignature()
	{
		$request = \Yii::$app->request;
		$signature = $request->get('signature','');
		$token = $this->appModel->wx_token;
		$timestamp = $request->get('timestamp','');
		$nonce = $request->get('nonce','');

		$tmpArr = [$token,$timestamp,$nonce];

		sort($tmpArr, SORT_STRING);
		$tmpStr = implode( $tmpArr );
		$tmpStr = sha1( $tmpStr );

		if( $tmpStr != $signature )
		{
			die('403 Forbidden');
		}
	}

	public function beforeAction($action)
	{
		$request = \Yii::$app->request;
		$this->appId = $request->get('app_id',-1);
		/** @var WxApp $appModel */
		$appModel = $this->appModel = WxApp::findOne($this->appId);

		if ($this->appModel === null)
		{
			die('403 Forbidden');
		}

		$this->checkSignature();

		if ($appModel->isEncrypted())
		{
			$this->encrypter = Encrypter::create($appModel->wx_app_id,$appModel->wx_token,$appModel->wx_encoding_aes_key);
		}


		if ($action->id === 'index')
		{
			\Yii::trace("\n\n\n".\Yii::$app->request->url."\n\n\n",WEIXIN_CATEGORY.'Request->get');
			\Yii::trace("\n\n\n".\Yii::$app->request->rawBody."\n\n\n",WEIXIN_CATEGORY.'Request->post');

			if (!is_null($this->encrypter))
			{
				$xml = $this->encrypter->decryptFromPost();
				if ($xml !== false)
				{
					\Yii::$app->request->setRawBody($xml);
				}
			}

		}
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}


	public function afterAction($action, $result)
	{
		if ($action->id === 'index')
		{
			\Yii::trace("\n\n\n".$result."\n\n\n" ,WEIXIN_CATEGORY.'Response');

			if (!is_null($this->encrypter))
			{
				$result = $this->encrypter->encryptToXml($result);
				\Yii::trace("\n\n\n".$result."\n\n\n" ,WEIXIN_CATEGORY.'Encrypted Response');
			}
		}
		return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
	}



}