<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * Class Articles
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property integer $type
 * @property integer $status
 * @property integer $create_time
 * @property integer $update_time
 * @property integer $creator
 */
class Articles extends ArticlesBase
{
    const TYPE_WEB_MODULE = 1;
    const TYPE_TOPIC = 2;
    const TYPE_NEWS = 3;


    public function fields()
    {
        return [
            'id',
            'title',
            'create_time'=>function($m)
            {
                return date('Y-m-d H:i',$m->create_time);
            },
        ];
    }

    public function beforeSave($insert)
    {
        if ($insert)
        {
            $this->create_time = time();
        }
        else
        {

        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
